export type PondQualityThreshold = {
    min_ph: number;
    max_ph: number;
    min_salinity: number;
    max_salinity: number;
    min_temperature: number;
    max_temperature: number;
    min_clarity: number;
    max_clarity: number;
    min_circulation: number;
    max_circulation: number;
    min_dissolved_oxygen: number;
    max_dissolved_oxygen: number;
    min_orp: number;
    max_orp: number;
    min_ammonia: number;
    max_ammonia: number;
    min_nitrate: number;
    max_nitrate: number;
    min_phosphate: number;
    max_phosphate: number;
    tolerance_rate: number;
  };