name: Deploy Development to VM

on:
  push:
    branches:
      - rafi/google_analytics

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm install

      - name: Run application tests
        run: npm run test:coverage
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker using ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: fiardiel
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/fiardiel/budidayaplus_fe:dev .
          docker push ghcr.io/fiardiel/budidayaplus_fe:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env: 
      API_BASE_URL: ${{ secrets.API_BASE_URL }}

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u fiardiel --password-stdin
            docker pull ghcr.io/fiardiel/budidayaplus_fe:dev
            docker stop budidayaplus_fe_dev || true
            docker rm budidayaplus_fe_dev || true
            docker run -d --name budidayaplus_fe_dev -p 3002:3000 \
              -e API_BASE_URL=${{ secrets.API_BASE_URL_DEV }} \
              ghcr.io/fiardiel/budidayaplus_fe:dev

